[theme]
# Skill Blue - Primary buttons and accents
primaryColor = "#1A33F5"

# Indigo - Dark Background for that professional "Dark Mode" feel
backgroundColor = "#150B3F"

# Darker Indigo - Secondary background (sidebar, cards)
secondaryBackgroundColor = "#0F072D"

# Aqua - Text color for high contrast against Indigo
textColor = "#7CF7F9"

# Font defaults
font = "sans serif"
